### ISSUE TITLE
Hide password input on lockdown-cli

### ISSUE THREAD

**Issue by nickavv** [StarChart-Labs/lockdown#27]
When entering passwords with the addkey function of lockdown-cli, the password is visible in the shell. Lots of command line tools I've used do not show characters as you're typing them for sensitive fields such as passwords, we should do the same thing

**Comment by romeara** [comment]
That is a bug - on other command lines, they are not shown (by design)

**Comment by romeara** [comment]
What shell environment and OS was this on?

**Comment by nickavv** [comment]
Git Bash on Windows 10

**Comment by romeara** [comment]
Resolved for versions after 0.1.1
